# Generated by Django 4.1 on 2022-08-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('release_data', models.CharField(max_length=100)),
                ('lte_exist', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
