# Generated by Django 4.1 on 2022-08-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='lte_exist',
            new_name='lte_exists',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='release_data',
            new_name='release_date',
        ),
    ]
