# Generated by Django 4.1 on 2022-08-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_alter_phone_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='slug',
        ),
    ]
