# Generated by Django 4.1 on 2022-08-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_remove_phone_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
